"""
準備 GitHub Pages 靜態輸出目錄（不包含後端／機密）。

用法：
  python scripts/prepare_github_pages.py
  python scripts/prepare_github_pages.py --api-base https://api.example.com --out .pages-dist

環境變數（可選）：
  ATTENDANCE_API_BASE  — 寫入 frontend config 的 Cloud API 根網址（勿含密鑰）
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "frontend"
DEFAULT_OUT = ROOT / ".pages-dist"


def _write_runtime_config(out_dir: Path, api_base: str, base_path: str) -> None:
    """覆寫／產生 config.runtime.js（由 HTML 在 config.js 前載入）。"""
    api = (api_base or "").rstrip("/")
    bp = (base_path or "/attendance").rstrip("/") or "/attendance"
    content = (
        "/* generated by prepare_github_pages.py - no secrets */\n"
        "window.AttendanceConfig = window.AttendanceConfig || {};\n"
        f'window.AttendanceConfig.API_BASE = {json.dumps(api)};\n'
        f'window.AttendanceConfig.BASE_PATH = {json.dumps(bp)};\n'
    )
    (out_dir / "static" / "js" / "config.runtime.js").write_text(content, encoding="utf-8")


def _inject_runtime_script(html: str) -> str:
    """在 config.js 之前插入 config.runtime.js。"""
    needle = 'src="static/js/config.js'
    inject = '<script src="static/js/config.runtime.js"></script>\n  <script ' + needle
    if "config.runtime.js" in html:
        return html
    if needle in html:
        return html.replace('<script ' + needle, inject, 1)
    # 相容單引號／其他寫法
    m = re.search(r'<script[^>]+config\.js[^>]*>', html)
    if m:
        tag = m.group(0)
        return html.replace(tag, '<script src="static/js/config.runtime.js"></script>\n  ' + tag, 1)
    return html


def prepare(out_dir: Path, api_base: str, base_path: str) -> None:
    if out_dir.exists():
        shutil.rmtree(out_dir)
    shutil.copytree(
        FRONTEND,
        out_dir,
        ignore=shutil.ignore_patterns("*.map", ".DS_Store"),
    )
    _write_runtime_config(out_dir, api_base, base_path)

    for name in ("index.html", "admin.html"):
        path = out_dir / name
        if not path.exists():
            continue
        html = path.read_text(encoding="utf-8")
        path.write_text(_inject_runtime_script(html), encoding="utf-8")

    # GitHub Pages：/attendance/admin/ → 提供 admin/index.html
    admin_dir = out_dir / "admin"
    admin_dir.mkdir(exist_ok=True)
    admin_src = out_dir / "admin.html"
    if admin_src.exists():
        shutil.copy2(admin_src, admin_dir / "index.html")
        # admin/index.html 內資源路徑需上移一層
        text = (admin_dir / "index.html").read_text(encoding="utf-8")
        text = text.replace('href="static/', 'href="../static/')
        text = text.replace('src="static/', 'src="../static/')
        text = text.replace('href="manifest.webmanifest"', 'href="../manifest.webmanifest"')
        (admin_dir / "index.html").write_text(text, encoding="utf-8")

    # 禁止把後端／資料庫誤拷進 Pages
    forbidden = [".env", ".secret_key", "attendance.sqlite3"]
    for root, _dirs, files in os.walk(out_dir):
        for f in files:
            if f in forbidden or f.endswith(".sqlite3"):
                raise SystemExit(f"拒絕輸出機密／資料庫檔案: {Path(root) / f}")

    print(f"Prepared GitHub Pages at {out_dir}")
    api_display = api_base if api_base else "(empty - set before production)"
    print(f"  BASE_PATH={base_path!r} API_BASE={api_display}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare static site for GitHub Pages")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--api-base",
        default=os.environ.get("ATTENDANCE_API_BASE", ""),
        help="Cloud API root URL (no trailing slash). Leave empty until known.",
    )
    parser.add_argument("--base-path", default="/attendance")
    args = parser.parse_args()
    prepare(args.out, args.api_base, args.base_path)


if __name__ == "__main__":
    main()
